apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-processor
  labels:
    app: phylax
spec:
  type: ClusterIP
  ports:
    - port: 2112
      targetPort: 2112
      protocol: TCP
      name: metrics
  selector:
    app: phylax